### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by davidgwyrick** [HChoiLab/functional-network#2]
Hey Disheng. Sorry to submit another issue, but the saying goes, you fix one problem and create another. The code is faster now, but now it seems like I have a memory issue. Whenever I try to run it on modestly large spiking data (say 120 trials, 1 second long, over 500 neurons), memory space slowly starts to be used up as the code processes each trial. The way you wrote the code, each time process_trial completes it is creating a NxNxW where W is the window size. For double floating point, that is only 0.2 Gb. So, 120 trials should be no problem. The jitter CCG is the same size, and is also per trial, so double that I guess. -> 50Gb.

But for some reason, the code crashes. I'm not sure where the issue is coming from, but I think it has to do with the trial length.  But I don't see how that is possible. e.g. everything else staying equal, 5sec long trials crashed vs 100ms trials did not.

In any case, I think the solution is to somehow reduce the need to save each trial, kind of like how you did in the previous version of the code. I added an internal array to the class to append to, but this doesn't work with the parallel version of the code. Do you know how to do that with joblib?

**Comment by DishengTang** [comment]
Hi David, thanks for bringing up this issue. I’ve encountered the same memory error before. The problem was that I initially stored the jittered CCG for each jitter sample in a large array, which, with a relatively high number of neurons and jitter samples, led to a memory crash. My solution was to initialize a single NxNxW array and accumulate the jittered CCGs into it, as we only care about the average, not each individual jitter sample. This is the current implementation, and I just tested it on a synthetic spike train with 500 neurons, 120 trials, and 1000 time bins—it didn’t exceed 40 GB of memory, so the calculation completed successfully.

However, keep in mind that total memory usage scales approximately with the number of cores used. If you’re using many cores to speed up the computation, you might need to balance the number of cores with the available system memory.

Regarding your comment about not saving each trial, we don’t save the full CCGs with a shape of NxNxtrxW (where tr is the number of trials). Moreover, we only initialize a minimal NxNxW jittered CCG for each trial. Could you clarify what you mean by further saving memory? I’d be happy to explore any suggestions you have.

**Comment by davidgwyrick** [comment]
I'm pretty sure process_trial returns an NxNxW matrix and it's called num_trial # of times. So that means the result list will be nTrialsxNxNxW. You then take the mean of that and only return a NxNxW matrix from calculate_mean_ccg_corrected

When you did your synthetic test, did you run it with the parallel option? I don't think that should matter for how the memory is being accumulated.

**Comment by DishengTang** [comment]
I see your point. The results are indeed saved for all trials, which seems unavoidable when using joblib for parallel processing along the trial dimension. While I can modify the non-parallel version to avoid saving the full results, this approach doesn’t translate well to the parallel version.

As you mentioned, the CCGs and jittered CCGs can take up around 40-50 GB of memory. If this is within your system's memory capacity, the next consideration is the memory usage within the process_trial function. For your case (500 neurons, 120 trials, 1000 time bins, and a CCG window of 100), this function uses approximately 0.8 GB per core. Therefore, using a large number of cores could still lead to memory issues so you may want to consider using fewer cores.

If the problem persists, one potential solution is to compute the jitter-corrected CCGs directly within process_trial. This would effectively halve the memory usage for that part of the process.

Moreover, I've noticed that during most of the runtime, memory usage is nearly proportional to the number of cores when parallel computing is enabled. This suggests that the memory allocations within the process_trial function likely account for the majority of memory consumption throughout the execution.
